import { GameShape } from './GameShape';

export const ruyLopez: GameShape = {
  whitePawn1: 'a-2',
  whitePawn2: 'b-2',
  whitePawn3: 'c-2',
  whitePawn4: 'd-2',
  whitePawn5: 'e-4',
  whitePawn6: 'f-2',
  whitePawn7: 'g-2',
  whitePawn8: 'h-2',
  whiteRook1: 'a-1',
  whiteRook2: 'h-1',
  whiteBishop1: 'c-1',
  whiteBishop2: 'b-5',
  whiteKnight1: 'b-1',
  whiteKnight2: 'f-3',
  whiteQueen: 'd-1',
  whiteKing: 'e-1',

  blackPawn1: 'a-7',
  blackPawn2: 'b-7',
  blackPawn3: 'c-7',
  blackPawn4: 'd-7',
  blackPawn5: 'e-5',
  blackPawn6: 'f-7',
  blackPawn7: 'g-7',
  blackPawn8: 'h-7',
  blackRook1: 'a-8',
  blackRook2: 'h-8',
  blackBishop1: 'c-8',
  blackBishop2: 'f-8',
  blackKnight1: 'c-6',
  blackKnight2: 'g-8',
  blackQueen: 'd-8',
  blackKing: 'e-8',
}